workflows:
  ios-testflight-preview:
    name: iOS TestFlight
    max_build_duration: 60 # minutes
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $FLUTTER_ROOT/.pub-cache
        - ios/Pods
        - node_modules
    scripts:
      # Install dependencies
      - name: Install Flutter dependencies
        script: cd client && flutter pub get

      # Remove problematic manual copy of ShareExtension.appex to avoid circular build errors
      - name: Remove manual copy of ShareExtension
        script: cd client && sed -i.bak '/ShareExtension.appex/d' ios/Runner.xcodeproj/project.pbxproj

      # Optional: Clean old builds for safety (doesn't delete caches)
      - name: Clean old build artifacts
        script: cd client && flutter clean

      # Build the iOS IPA (release)
      - name: Build iOS IPA
        script: cd client && flutter build ipa --release

      # Code sign (handled by Codemagic's automatic signing)
      - name: Code sign IPA
        script: |
          # Codemagic automatically signs when distributing to TestFlight
          echo "Code signing handled via Codemagic"

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_KEY
        issuer_id: $APP_STORE_ISSUER
        key_id: $APP_STORE_KEY_ID
        submit_to_testflight: true # Automatically makes the build available to testers
        beta_groups:
          - RecipEase Testing # Name of your TestFlight tester group
