workflows:
  flutter-ios-simulator:
    name: Flutter iOS Simulator

    environment:
      flutter: 3.32.5

      xcode: 16.4

    scripts:
      - cd client && flutter build ios --release --simulator # --flavor is optional

    artifacts:
      - build/ios/iphonesimulator/Runner.app
