workflows:
  ios-testflight-preview:
    name: iOS TestFlight
    max_build_duration: 60 # minutes
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $FLUTTER_ROOT/.pub-cache
        - ios/Pods
        - node_modules
    scripts:
      # Install dependencies
      - name: Install Flutter dependencies
        script: cd client && flutter pub get

      # Optional: Clean old builds for safety (doesn't delete caches)
      - name: Clean old build artifacts
        script: cd client && flutter clean

      # Build the iOS IPA with automatic ShareExtension embedding (release)
      # This uses our enhanced build script that ensures ShareExtension.appex
      # is properly embedded in the final IPA for distribution
      - name: Build iOS IPA with ShareExtension
        script: cd client && flutter build ipa --release --export-options-plist=ios/export_options.plist

      # Code sign (handled by Codemagic's automatic signing)
      - name: Code sign IPA
        script: |
          # Codemagic automatically signs when distributing to TestFlight
          echo "Code signing handled via Codemagic"

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_KEY
        issuer_id: $APP_STORE_ISSUER
        key_id: $APP_STORE_KEY_ID
        submit_to_testflight: true # Automatically makes the build available to testers
        beta_groups:
          - RecipEase Testing # Name of your TestFlight tester group

  # Add a new workflow for development builds
  ios-development:
    name: iOS Development Build
    max_build_duration: 60 # minutes
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $FLUTTER_ROOT/.pub-cache
        - ios/Pods
        - node_modules
    scripts:
      - name: Install Flutter dependencies
        script: cd client && flutter pub get

      - name: Make build scripts executable
        script: cd client && chmod +x flutter_build.sh

      - name: Clean old build artifacts
        script: cd client && flutter clean

      - name: Build iOS Development IPA
        script: cd client && flutter build ipa --debug --export-options-plist=ios/export_options_development.plist

    artifacts:
      - build/ios/ipa/*.ipa
