platform :ios, '14.0'

# Define the path to your Flutter project root
flutter_application_path = File.expand_path('..', __dir__)

# Load Flutter CocoaPods helper
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Install all Flutter plugin pods
  install_all_flutter_pods(flutter_application_path)
end

# Post-install hook to set build settings
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end
